---
:workspace_path: 'c:\path_to_workspace'
:dev_branch: Main
:int_branch: Integration
:merge_int_checkin_note: Full merge from Main to Integration
:username: username
:password: password
:custom_commands_file: custom_commands.rb
:tf_path: 'C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\tf.exe'
